spring:
  sql.init.mode: always
  datasource:

    url: jdbc:mysql://localhost:3306/db_scholarship

    driver-class-name: com.mysql.cj.jdbc.Driver

    username: root


    password: root




=======
    password: root

  jpa:

    hibernate:

      ddl-auto: create-drop

    show-sql: false

    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
