spring:
  sql.init.mode: never
  datasource:

    url: jdbc:mysql://localhost:3306/db_scholarship?createDatabaseIfNotExist=true

    driver-class-name: com.mysql.cj.jdbc.Driver

    username: root

    password: bc33441514




  jpa:

    hibernate:

      ddl-auto: update

    show-sql: false

    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
